repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-toml
    - id: mixed-line-ending
    - id: check-merge-conflict
    - id: check-json
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
- repo: https://github.com/asottile/pyupgrade
  rev: ""
  hooks:
    - id: pyupgrade
      language_version: python3.10
      args: []
